### ISSUE TITLE
Memory alpha wiki doesn't work

### ISSUE THREAD

**Issue by Akronix** [Grasia/WikiChron-networks#51]
I've tried several time ranges for memory alpha wiki for [co-editing network](http://staging.wikichron.science/networks/app/?wikis=memory-alpha.fandom.com&network=co_editing_network), [talk network](http://staging.wikichron.science/networks/app/?wikis=memory-alpha.fandom.com&network=talk_pages_network) and [user talk network](http://staging.wikichron.science/networks/app/?wikis=memory-alpha.fandom.com&network=user_talk_network), and none of them seem to work for this wiki.

The app loads but when finished, nothing is displayed in the place of the cytoscape component. Since this is a huge wiki, I don't think it is empty but it's something else.

**Comment by Akronix** [comment]
Error in server side:
```
Loading csv for memory-alpha.wikia.com.csv
/root/staging-WikiChron/wikichron/dash/apps/networks/data_controller.py:84: DtypeWarning:

Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.

!!Loaded csv for memory-alpha.wikia.com.csv
 * [Timing] Loading memory-alpha.wikia.com.csv : 90.87201596994419 seconds
[2019-03-27 21:47:31 +0100] [28411] [DEBUG] Ignoring EPIPE
[2019-03-27 21:47:31 +0100] [28411] [DEBUG] POST /networks/app/_dash-update-component
[2019-03-27 21:47:31 +0100] [28411] [DEBUG] POST /networks/app/_dash-update-component
 * [Info] Building the network....
 * [Timing] Loading csvs : 4.471047046943568 seconds
 * [Info] Starting calculations....
[2019-03-27 21:47:44,700] ERROR in app: Exception on /networks/app/_dash-update-component [POST]
Traceback (most recent call last):
  File "/root/staging-WikiChron/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/staging-WikiChron/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/staging-WikiChron/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/staging-WikiChron/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/root/staging-WikiChron/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/staging-WikiChron/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/staging-WikiChron/venv/lib/python3.6/site-packages/dash/dash.py", line 1073, in dispatch
    response.set_data(self.callback_map[output]['callback'](*args))
  File "/root/staging-WikiChron/venv/lib/python3.6/site-packages/dash/dash.py", line 969, in add_context
    output_value = func(*args, **kwargs)
  File "/root/staging-WikiChron/wikichron/dash/apps/networks/networks/controls_sidebar_decorator/CoEditingControlsSidebarDecorator.py", line 198, in update_network
    network = data_controller.get_network(wiki, network_code, lower_bound, upper_bound)
  File "/root/staging-WikiChron/venv/lib/python3.6/site-packages/flask_caching/__init__.py", line 686, in decorated_function
    rv = f(*args, **kwargs)
  File "/root/staging-WikiChron/wikichron/dash/apps/networks/data_controller.py", line 69, in get_network
    network.build_network(df=df, lower_bound = lower_bound, upper_bound = upper_bound)
  File "/root/staging-WikiChron/wikichron/dash/apps/networks/networks/models/BaseNetwork.py", line 250, in build_network
    self.generate_from_pandas(dff)
  File "/root/staging-WikiChron/wikichron/dash/apps/networks/networks/models/TalkPagesNetwork.py", line 97, in generate_from_pandas
    if int(r['contributor_id']) not in user_per_page[r['page_id']]:
KeyError: '105715'
```

**Comment by Akronix** [comment]
I just realized that there are issues in WikiChron classic to with this wiki. It doesn't crash though, but it throws this warning:
```
wikichron/main.py:86: DtypeWarning:

Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
```

**Comment by Akronix** [comment]
Checking the browser console I'm getting this error:
```
index.js:464 POST http://staging.wikichron.science/networks/app/_dash-update-component 413 (Request Entity Too Large)
```
Which seems more related to the actual problem than the previous one.

**Comment by Akronix** [comment]
Some reference on this: https://stackoverflow.com/questions/19459236/how-to-handle-413-request-entity-too-large-in-python-flask-server
